baseurl: "/sebastian.github.io" # Set to "/<repo>" for project pages
url: "https://sssolano.github.io" # Owner domain remains the same

# Jekyll settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
